### ISSUE TITLE
healthcheck error

### ISSUE THREAD

**Issue by fastfading** [AGou-ops/dotfiles#11]
## The following errors have been detected:
  - ERROR: lua(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 1141 for language lua
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/xxx/.vim/plugged/nvim-treesitter/queries/lua/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 1141 for language lua
  - ERROR: help(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100 for language help
    help(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/xxx/.vim/plugged/nvim-treesitter/queries/help/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 100 for language help

**Comment by AGou-ops** [comment]
命令行模式下，运行一下`TSUpdateSync`这个命令.
