### ISSUE TITLE
toggleterm怎么调用出多个teriminal呢，用什么快捷键呢，在哪里配置

### ISSUE THREAD

**Issue by tbago** [AGou-ops/dotfiles#15]
还有怎么在toggleterm的terminal和窗口之间切换呢

**Comment by AGou-ops** [comment]
toggleterm我一般只调用一个出来，调用多个我不太清楚，没这方面需求，你可以看看toggleterm的readme有没有.
快捷键基本都在`lua/config/keymaps.lua`里面，另外还有少许插件单独的快捷键设置在插件的配置文件中.

**Comment by AGou-ops** [comment]
toggleterm我一般只调用一个出来，调用多个我不太清楚，没这方面需求，你可以看看toggleterm的readme有没有.
快捷键基本都在`lua/config/keymaps.lua`里面，另外还有少许插件单独的快捷键设置在插件的配置文件中.
