### ISSUE TITLE
使用telescope时有问题

### ISSUE THREAD

**Issue by baiyecha** [AGou-ops/dotfiles#17]
<img width="1532" alt="企业微信截图_530fd9aa-fc13-4bf7-bc23-ec82a25f4561" src="https://user-images.githubusercontent.com/23014506/227195439-bce96edd-23fe-43ad-b0b9-9fa4aa967c46.png">

我进入一个项目，使用telescope 打开一个文件是正常的，然后我再次使用telescope 打开另一个文件，百分之百出现问题，我不知道是什么原因，大佬有遇到过嘛

**Comment by AGou-ops** [comment]
还有我看你那个字体也有问题，找个Nerd Fonts换上就行了，可以在 https://github.com/ryanoasis/nerd-fonts 这里下载你喜欢的字体.

**Comment by baiyecha** [comment]
我试了是正常的，只有trans.health有问题，这个应该没有关系
然后我用其他的命令试了一下，比如Telescope find_files 这个就会有我说的情况
但是我用Telescope oldfiles 就是正常的

**Comment by AGou-ops** [comment]
> 我试了是正常的，只有trans.health有问题，这个应该没有关系 然后我用其他的命令试了一下，比如Telescope find_files 这个就会有我说的情况 但是我用Telescope oldfiles 就是正常的


欸，不对，你这个报错是treesitter报的错，你手动重新装一下treesitter试试，并将treessitter升级到最新.

这里有个[issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/4421)，和你的报错一样，已经被修复了，你可以去看看，

**Comment by baiyecha** [comment]
大佬能方便加一下你的联系吗，想请教您一下配置的问题

**Comment by baiyecha** [comment]
https://github.com/LunarVim/LunarVim/issues/2220

**Comment by AGou-ops** [comment]
> [LunarVim/LunarVim#2220](https://github.com/LunarVim/LunarVim/issues/2220) 建议配一下Telescope live_grep的过滤文件，我的一个项目和上面一样直接卡死了 不知道大佬有没有遇到过
> 
> 然后还有一个工作目录的问题，我发现Telescope find_files 选择一个文件之后，:pwd的路径就变了，然后再Telescope find_files 就是当前目录的文件了，我弃用了autochdir，每次nvim命令就是当前的路径，并且不会改变了。这样配置之后treesitter的问题也没有了，我不知道具体的原因
> 
> 另外大佬是习惯用Yggdroot/LeaderF吗，我看你视频演示的感觉Telescope比较6，这两个功能是不是有些重合，我删除了LeaderF，不知道会不会影响其他功能

我这telescope live_grep打开前端项目会有一点点卡，但不至于卡死，可能是我的项目文件少吧，这段时间有其他事要忙，就没怎么折腾配置文件了，有空我也看看加上这个过滤文件吧.

`autochdir`看个人习惯吧，我是习惯这个样子.

telescope和leaderf我混着用的，功能是有些重复，但各有各的优点，删除leaderF没啥问题，记得把`lua/config/keymaps.lua`里面的leaderF键盘映射也删了就行了.

**Comment by baiyecha** [comment]
收到，感谢大佬，这个issue可以关闭啦
