### ISSUE TITLE
toggleterm

### ISSUE THREAD

**Issue by Roc-zhou** [AGou-ops/dotfiles#5]
下面删掉就可以了应该
![image](https://user-images.githubusercontent.com/33691840/162352684-22fbe2ef-67c4-4800-8d1c-0352808c3bdd.png)

**Comment by AGou-ops** [comment]
@Roc-zhou 改用`vim-script`配置了，这个地方用lua调用api配置快捷键不是很清楚，很奇怪，也懒得再深究了。如果你想用lua配置快捷键的话，参考我[lsp的快捷键配置](https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/lua/AGou/lsp.lua#L8-L46)

![image](https://user-images.githubusercontent.com/57939102/162357644-e4262ad9-a846-4612-8129-824d736f5c41.png)
