### ISSUE TITLE
Can't require AGou lua module

### ISSUE THREAD

**Issue by gogoafuzzz** [AGou-ops/dotfiles#7]
Hi @AGou-ops
謝謝你提供的配置，看了視頻後覺得很棒！😆

目前使用 [neovim-with-lua](https://github.com/AGou-ops/dotfiles/tree/master/neovim-with-lua) 的配置後，出現以下的錯誤。

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12717486/182021535-b1e5dce1-f4e8-4eb2-a171-cd7afdd9b588.png">

**Comment by AGou-ops** [comment]
@gogoafuzzz  你是不是放错地方了？这个配置文件需要放到家目录下面的，比如`/home/agou/.config/nvim`这个文件夹.

**Comment by gogoafuzzz** [comment]
@AGou-ops 谢谢提醒 ~ 我这边重新调整路径后，已经可以载入 AGuo lua module 了，不过又出现下面的错误，确认了一下 `lua/AGuo` 目录下没有 `impatient` 模组，需要什么额外设置吗？

```
Error detected while processing /root/.config/nvim/init.vim:
line  566:
E5108: Error executing lua /root/.vim/plugged/impatient.nvim/lua/impatient.lua:423: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        /root/.vim/plugged/impatient.nvim/lua/impatient.lua:423: in function 'setup'
        /root/.vim/plugged/impatient.nvim/lua/impatient.lua:443: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/lua/AGou/init.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing /root/.vim/plugged/nvim-treesitter-context/plugin/treesitter-context.vim:
```

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/12717486/182023076-83f4051c-06ce-45ea-b17f-496b01f93b83.png">

**Comment by gogoafuzzz** [comment]
@AGou-ops 有了！谢谢提醒 ~
