### ISSUE TITLE
[lua]attempt to index field 'window' (a nil value)

### ISSUE THREAD

**Issue by zxxjyn** [AGou-ops/dotfiles#8]
你好，我所有的插件安装完成后，打开nvim提示如下错误。
使用主目录下的 init.vim 和 neovim-with-lua 的 init.vim 都会提示相同错误。

```shell
Error detected while processing /root/.config/nvim/init.vim:

line  565:
E5108: Error executing lua /root/.config/nvim/lua/AGou/nvim-cmp.lua:27: attempt to index field 'window' (a nil value)
stack traceback:
        /root/.config/nvim/lua/AGou/nvim-cmp.lua:27: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/lua/AGou/init.lua:9: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

以下是插件安装以及.config/nvim目录
![image](https://user-images.githubusercontent.com/42338930/183970980-640e2f52-338b-45c5-92df-c8699b419472.png)
![image](https://user-images.githubusercontent.com/42338930/183971271-6afe3001-bb08-47fd-b6b4-e313e0120cf4.png)

**Comment by AGou-ops** [comment]
看起来应该是你的`nvim-cmp`这个插件没有成功安装，你退出，然后重新`:PlugInstall`一下，看看还有没有没安装好的。

或者你可以在`~/.vim/plugged`里面检查一下对应的文件夹.

**Comment by zxxjyn** [comment]
问题已经解决。是nvim-cmp插件的问题
解决方法：plugged目录rm掉nvim-cmp，重新PlugInstall一下就ok了。
目前已正常跑起来，谢谢。
