### ISSUE TITLE
需要快速使用指南

### ISSUE THREAD

**Issue by fastfading** [AGou-ops/dotfiles#9]
快捷键
功能说明
等等，
插件虽好，  不知道怎么使用啊

**Comment by fastfading** [comment]
比如 
outline
floatterm 
goto definiton  / reference 
golang 的一些操作 怎么用

**Comment by fastfading** [comment]
很多功能不work
需要安装额外包

,fg
rg: Executable not found

,fF
ranger ： Executable not found

**Comment by fastfading** [comment]
sf
golang   reference  不能跳转到文件，

**Comment by AGou-ops** [comment]
> 很多功能不work 需要安装额外包
> 
> ,fg rg: Executable not found
> 
> ,fF ranger ： Executable not found
> 
> vim with python3
> 
> LeaderF 这个好难装， 卡在这了 好像还要和rg 联动
> 
> Error detected while processing /Users/huzhang2/.vim/plugged/LeaderF/autoload/leaderf/Any.vim[10]../Users/huzhang2/.vim/plugged/LeaderF/autoload/leaderf.vim : line 18: Error: LeaderF requires vim compiled with +python or +python3 Error: LeaderF requires vim compiled with +python or +python3 Error detected while processing /Users/huzhang2/.vim/plugged/LeaderF/autoload/leaderf/Any.vim: line 10: E117: Unknown function: leaderf#versionCheck line 14: E121: Undefined variable: g:Lf_py Error detected while processing function leaderf#Any#start[4]..script /Users/huzhang2/.vim/plugged/LeaderF/autoload/leaderf.vim: line 18: Error: LeaderF requires vim compiled with +python or +python3 Error detected while processing function leaderf#Any#start: line 4: E117: Unknown function: leaderf#LfPy

```bash
pip2 install --user --upgrade neovim
pip3 install --user --upgrade neovim
```

leadF的依赖问题， 安装Python2 和 Python3 支持就行了.

**Comment by AGou-ops** [comment]
> 比如 outline floatterm goto definiton / reference golang 的一些操作 怎么用 全目录搜索 文本替换
> 
> 等等。。。

这个在`lua/AGou/lsp.lua`文件里面有写，都是快捷键，看英文就行了.
![image](https://user-images.githubusercontent.com/57939102/202903030-7293f545-5b84-402a-9a17-f45d37a3f1ff.png)

**Comment by AGou-ops** [comment]
> 比如 outline floatterm goto definiton / reference golang 的一些操作 怎么用 全目录搜索 文本替换
> 
> 等等。。。

这些你看`keymap.vim`这个文件就行了，快捷键都在这里面，我都有注释是哪个插件的快捷键.

实在是没空写那么详细了.😂

**Comment by fastfading** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
这个快捷键是什么

**Comment by AGou-ops** [comment]
> <img alt="image" width="935" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
> 
> 这个快捷键是什么

那个是关闭buffer，鼠标可以直接点击，关闭当前buffer的快捷键是`C-q`.

**Comment by fastfading** [comment]
> > <img alt="image" width="935" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
> > 这个快捷键是什么
> 
> 那个是关闭buffer，鼠标可以直接点击，关闭当前buffer的快捷键是`C-q`.

鼠标点x  和ctrl+q       :db         <leader>dd  行为是不一样的

只有 鼠标点x  能完成完美关闭动作，并跳到上一个没有关闭的页面，  这个和ide 行为基本一致
  其他会吧窗口关掉，然后留出一片空白。

**Comment by AGou-ops** [comment]
> > > <img alt="image" width="935" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
> > > 这个快捷键是什么
> > 
> > 
> > 那个是关闭buffer，鼠标可以直接点击，关闭当前buffer的快捷键是`C-q`.
> 
> 鼠标点x 和ctrl+q :bd dd 行为是不一样的
> 
> 只有 鼠标点x 能完成完美关闭动作，并跳到上一个没有关闭的页面， 这个和ide 行为基本一致 其他会吧窗口关掉，然后留出一片空白。

`C-q`我是映射的`C-w q`，这个快捷键是关闭窗口，比如分屏的时候关闭当前窗口保留另外一个，点x号，用的是bufdelete，会保留当前的window，也就是你上面说的.  我一般单窗口多buffer鼠标点击`x`号或者使用`:bd `来删除buffer，多窗口分屏的时候用`C-q`.

具体是在下面这两个地方设置的：

> https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/keymaps.vim#L232

> https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/lua/AGou/nvim-bufferline.lua#L6-L8

**Comment by fastfading** [comment]
> > > > <img alt="image" width="935" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
> > > > 这个快捷键是什么
> > > 
> > > 
> > > 那个是关闭buffer，鼠标可以直接点击，关闭当前buffer的快捷键是`C-q`.
> > 
> > 
> > 鼠标点x 和ctrl+q :bd dd 行为是不一样的
> > 只有 鼠标点x 能完成完美关闭动作，并跳到上一个没有关闭的页面， 这个和ide 行为基本一致 其他会吧窗口关掉，然后留出一片空白。
> 
> `C-q`我是映射的`C-w q`，这个快捷键是关闭窗口，比如分屏的时候关闭当前窗口保留另外一个，点`x`号用的是bufdelete，会保留当前的window，也就是你上面说的. 我一般单窗口多buffer鼠标点击`x`号或者使用`:bd `来删除buffer，多窗口分屏的时候用`C-q`.
> 
> 具体是在下面这两个地方设置的：
> 
> > https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/keymaps.vim#L232
> 
> > https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/lua/AGou/nvim-bufferline.lua#L6-L8

要用  :Bdelete  
bdelete 和 Bdelete  还不一样

**Comment by fastfading** [comment]
另外 ctrl-i  的行为被篡改了， 我希望是往前跳， 和vim 一样。     
    我改了 keymaps 也不行

**Comment by AGou-ops** [comment]
> > > > > <img alt="image" width="935" src="https://user-images.githubusercontent.com/8351732/202972367-c1ea80a4-a33b-48c7-aef5-b71f518fd8e8.png">
> > > > > 这个快捷键是什么
> > > > 
> > > > 
> > > > 那个是关闭buffer，鼠标可以直接点击，关闭当前buffer的快捷键是`C-q`.
> > > 
> > > 
> > > 鼠标点x 和ctrl+q :bd dd 行为是不一样的
> > > 只有 鼠标点x 能完成完美关闭动作，并跳到上一个没有关闭的页面， 这个和ide 行为基本一致 其他会吧窗口关掉，然后留出一片空白。
> > 
> > 
> > `C-q`我是映射的`C-w q`，这个快捷键是关闭窗口，比如分屏的时候关闭当前窗口保留另外一个，点`x`号用的是bufdelete，会保留当前的window，也就是你上面说的. 我一般单窗口多buffer鼠标点击`x`号或者使用`:bd `来删除buffer，多窗口分屏的时候用`C-q`.
> > 具体是在下面这两个地方设置的：
> > > https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/keymaps.vim#L232
> > 
> > 
> > > https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/lua/AGou/nvim-bufferline.lua#L6-L8
> 
> 要用 :Bdelete bdelete 和 Bdelete 还不一样

...

我用的不就是你说的那个`Bdelete`？`Bdelete`是[这个插件](https://github.com/famiu/bufdelete.nvim)提供的，我用require调用了.

https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/lua/AGou/nvim-bufferline.lua#L7

```bash
require('bufdelete').bufdelete(bufnum, true)
```

**Comment by AGou-ops** [comment]
> 另外 ctrl-i 的行为被篡改了， 我希望是往前跳， 和vim 一样。 我改了 keymaps 也不行

快捷键都是根据自己的习惯改的，不喜欢或者不适合你可以直接改，我上面也说了，都在`keymap.vim`和`lsp.lua`这两个文件里面.

你说的`C-i`不就在这里？

https://github.com/AGou-ops/dotfiles/blob/master/neovim-with-lua/keymaps.vim#L49
